// See https://github.com/lightbend/config/blob/main/HOCON.md for the HOCON syntax.

ditto {
  apiKeySecretName = "DITTO-API-KEY"
  providerName = "freedger-api"
  tokenExpiresIn = "PT24H"
}
openExchangeRates {
  appIdSecretName = "OPEN-EXCHANGE-RATES-APP-ID"
  configPath = "openexchangerates/config.json"
}
auth {
  // Directly use managed identity for the cloud environment to speed
  // up the cold start time.
  useManagedIdentity = true
}
quotesUpdateDays = 20
