// See https://github.com/lightbend/config/blob/main/HOCON.md for the HOCON syntax.

ditto {
  apiKeySecretName = "DITTO-API-KEY"
  providerName = "freedger-api"
  tokenExpiresIn = "PT24H"
}
openExchangeRates {
  include required(classpath("openexchangerates.conf"))
}
auth {
  // Directly use managed identity for the cloud environment to speed
  // up the cold start time.
  useManagedIdentity = true
  // Client ID of the user-assigned managed identity
  // Decided from "AZURE_CLIENT_ID" environment variable or "" if not set
  managedIdentityClientId = ${?AZURE_CLIENT_ID}""
}
