// See https://github.com/lightbend/config/blob/main/HOCON.md for the HOCON syntax.
// Use hyphen-separated keys as suggested by the documentation.

ditto {
  api-key-secret-name = "DITTO-API-KEY"
  provider-name = "freedger-api"
  token-expires-in = "PT24H"
}
open-exchange-rates {
  include required(classpath("openexchangerates.conf"))
}
auth {
  // Directly use managed identity for the cloud environment to speed
  // up the cold start time.
  use-managed-identity = true
}
