include required(classpath("base.conf"))

keyVault {
  url = "https://freedger-dev.vault.azure.net/"
}
auth {
  // Client ID of the user-assigned managed identity
  managedIdentityClientId = "fc2ea029-4e30-44e6-8a91-ee77b0d1b222"
  issuer = "https://freedger-dev.jp.auth0.com/"
  audience = "https://api.freedger.org/"
  jwks = "https://freedger-dev.jp.auth0.com/.well-known/jwks.json"
}
ditto {
  appId = "46190b14-5d64-477c-b5b6-ba2d15e998be"
  apiBaseUrl = "https://i83inp.cloud.dittolive.app/46190b14-5d64-477c-b5b6-ba2d15e998be/api/v5"
}

