############################################################
# Default Logging Configuration File
############################################################
handlers = java.util.logging.ConsoleHandler

# Default global logging level
.level = INFO

############################################################
# Handler specific properties
############################################################

# ConsoleHandler configuration
# Notice that the settings here won't affect the `traces` events in App Insights.
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
# Example:
#   [org.freedger.controller.LedgersApi] Error processing create ledger request
#   java.lang.NullPointerException: Cannot invoke "org.freedger.domain.Ledger.getName()" because "ledger" is null
#	  at org.freedger.service.LedgerService.create(LedgerService.java:45)
#	  at org.freedger.controller.LedgersApi.createLedger(LedgersApi.java:149)
java.util.logging.SimpleFormatter.format=[%2$s] %5$s%6$s%n
